#!/usr/bin/env bash
files=$1
export NODE_ENV=tests-unit
if [ "$files" != "" ] ; then
  mocha --require ts-node/register --require tsconfig-paths/register --exit "$files"
else
  mocha --require ts-node/register --require tsconfig-paths/register --exit tests/unit/models/* tests/unit/libs/* tests/unit/controllers/*
fi
