#!/usr/bin/env bash
[ -z "$NODE_ENV" ] && export NODE_ENV=dev

server_port=$(node -p "require('config').port")
# supervisor pid is used by tests/api/scripts
supervisor_pid_file="./run/${server_port}-supervisor"

supervisor \
  --watch server,config,db/couchdb \
  --save-pid  $supervisor_pid_file \
  --extensions ts,js,json,hbs \
  --exec sh \
  -- -c 'ts-node -r tsconfig-paths/register server/server.ts'
